language: node_js
node_js:
  - "10.14.2"

cache: npm

branches:
  except:
    - gh-pages

install:
  - npm install

script:
  - npm run lint
  - npm run build

deploy:
  local-dir: ./build
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: site
